apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort # ServiceType:
                 # ClusterIP(default) stable internal cluster IP
                 # NodePort: exposes the app outside of the cluster by adding a
                 # cluster wide port on top of ClusterIP
                 # LoadBalancer: integrates NodePort with cloud-based load
                 # balancers
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-world
