#!/bin/bash

# Script Def : SerhattanDahaAkilli - Serhat mı daha hızlı script mi?

echo -n "Bir sayi soyle : "
read n1
echo -n "Bir sayi daha soyle :"
read n2

if [ $n1 -gt $n2 ]; then
	echo "$n1 daha büyüktür."
else
	echo "$n2 daha büyüktür."
fi

echo "Ya ne oldu?!"
