#!/bin/bash

# caseStatement - Script Def : Case yapısının kullanımına bir ornek


######################################################
# Case yapısı diger dillerdeki syntax göre biraz farklılık var.
#####################################################

echo -n "Enter a number between 1 and 3 inclusive > "
read number

case $number in
	1 ) echo "You entered one."
		;;
	2 ) echo "You entered two."
		;;
	3 ) echo "You entered three."
		;;
	* ) echo "You did not entered a number between 1 and 3."
esac
