#!/bin/bash

# detectingArgument - Script Def : Girdigimiz komuttaki argumanlari tespit eder.

# $0 degiskeni komutun kendisini, sonra gelenler ise parametleri saklar.

# $# degiskeni ise toplam parametre sayisini saklar.

if [ "$1" != "" ]; then 
	echo "Positional parameter 1 contains something"
else 
	echo "Positional parameter 1 is empty"
fi

echo ""

if [ $# -gt 0 ]; then
	echo "Your command line contains $# arguments"
else 
	echo "Your command line contains no arguments"
fi
